### ISSUE TITLE
Custom stylesheet for Markdown

### ISSUE THREAD

**Issue by ceanela** [NoahRic/MarkdownMode#16]
It would be highly desirable if I could set a default stylesheet for my Markdown, or even reference one.

**Comment by drewnoakes** [comment]
Agreed. There are really nice styles for markdown on sites like Github. The fact they look so good is a motivation for the use of markdown, imho.

I too would like to see this extension produce more attractive output.

Perhaps I can find time to help with this. @NoahRic would you accept a PR, and if so could you provide some pointers on where to start?

**Comment by NoahRic** [comment]
I would accept a PR, though I've been incredibly tardy about pulling them in and updating things on the gallery.

I'd guess the easiest way would be to avoid trying to figure out something like a modeline for the style sheet (if there isn't already a standard for that); a comment that references it, or maybe even just implicitly looking for something like style.css in the same directory and putting a reference inside the preview window.

Sorry I'm not more helpful, I haven't done much markdown or VS stuff in a few years.
