### ISSUE TITLE
Cyrillic language

### ISSUE THREAD

**Issue by vko-online** [NoahRic/MarkdownMode#23]
![asdsad](https://cloud.githubusercontent.com/assets/4560099/4008796/b02bfc46-29db-11e4-8d5b-964afe4e716f.jpg)
Doesnt support!

**Comment by i-korob** [comment]
hi, use this
1. find and save original file **MarkdownMode.dll**
   ![first_step](https://cloud.githubusercontent.com/assets/4510136/13668350/3b67252e-e6cd-11e5-8aa4-71721cc5b3aa.PNG)
2. open in [CFF Explorer](http://www.ntcore.com/exsuite.php) and find string "**utf**" at _.NET Directory / MetaData Streams / #US_
   ![second_step](https://cloud.githubusercontent.com/assets/4510136/13668496/27ce9582-e6ce-11e5-8a39-a482c41583a9.PNG)
3. modify raw data  "**005C 0022 003E 000D**" to "**0022 003E 000D 000A**"
   ![change_step](https://cloud.githubusercontent.com/assets/4510136/13668517/45499c74-e6ce-11e5-9c94-646a5110a804.PNG)
4. save with overwrite 
   ![save_step](https://cloud.githubusercontent.com/assets/4510136/13668521/4a09db16-e6ce-11e5-981e-463508123aa3.PNG)
5. enjoy
   ![finish_step](https://cloud.githubusercontent.com/assets/4510136/13668345/3605989a-e6cd-11e5-8144-58b90c13bd4a.PNG)

**Comment by nzmedet** [comment]
Serious? Maybe better throw that library away
