### ISSUE TITLE
Support for Visual Studio 2015

### ISSUE THREAD

**Issue by 2moveit** [NoahRic/MarkdownMode#28]
Currently it's missing on NuGet and/because the vsix cannot be installed on VS 2015

**Comment by drewnoakes** [comment]
+1. I miss this extension while working in VS2015.

**Comment by drewnoakes** [comment]
_Web Essentials_ is an alternative for VS2015.

* http://vswebessentials.com/changelog
* https://visualstudiogallery.msdn.microsoft.com/ee6e6d8c-c837-41fb-886a-6b50ae2d06a2

I haven't used it for long yet, but so far I think I prefer it. The formatting is much nicer in the preview window (though this should be an easy fix for this extension too). The markdown editor is a lot less colourful/styled, which isn't necessarily better or worse but will take some getting used to.

The only downside I see so far is that Web Essentials installs all sorts of other things that you mightn't want/need if you don't do web development.

**Comment by 2moveit** [comment]
Thanks for the hint. Will check it out, too.

**Comment by voltagex** [comment]
Any updates on this?

**Comment by NoahRic** [comment]
Hoping to get to it this weekend. I did a few a week ago, but I didn't
finish them all up yet.

**Comment by voltagex** [comment]
Thanks @NoahRic - I should have time this weekend, too (UTC+11), let me know if there's anything you need a hand with / second set of eyes

**Comment by NoahRic** [comment]
Actually, if anyone wants to contribute a theme change (better colors),
I'll pull it down and put it in the build I upload. I know it's a pretty
standard complaint that I picked some terrible colors as defaults, so I'd
be happy to fix two things at the same time :)

**Comment by drewnoakes** [comment]
Looking forward to an updated version of this extension!

I made some CSS for the Chrome extension "MarkDown Preview Plus" which produced what I think is quite nice markdown rendering. It's pretty similar to what GitHub uses, which I think is a good target.

http://pastebin.com/YLw3LKnr

Perhaps it'll be useful.

**Comment by NoahRic** [comment]
Should support VS2015 now.
