### ISSUE TITLE
Incorrect table preview (v 2.7)

### ISSUE THREAD

**Issue by addnot** [NoahRic/MarkdownMode#31]
![capture](https://cloud.githubusercontent.com/assets/16011103/12222897/c5027608-b7d9-11e5-8ad3-ca98cafefba0.PNG)
original file:
[01-Introduction.zip](https://github.com/NoahRic/MarkdownMode/files/84649/01-Introduction.zip)

**Comment by immeraufdemhund** [comment]
Same is true with this

```
|   Score   | Modifier |   Score   | Modifier |   Score   | Modifier |   Score   | Modifier |
|:---------:|:--------:|:---------:|:--------:|:---------:|:--------:|:---------:|:--------:|
|   __1__   |    -5    |   __6__   |    -2    |  __11__   |     0    |  __16__   |    +3    |
|   __2__   |    -4    |   __7__   |    -2    |  __12__   |    +1    |  __17__   |    +3    |
|   __3__   |    -4    |   __8__   |    -1    |  __13__   |    +1    |  __18__   |    +4    |
|   __4__   |    -3    |   __9__   |    -1    |  __14__   |    +2    |  __19__   |    +4    |
|   __5__   |    -3    |  __10__   |     0    |  __15__   |    +2    |  __20__   |    +5    |
```

I would expect to see this

| Score | Modifier | Score | Modifier | Score | Modifier | Score | Modifier |
| :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
| **1** | -5 | **6** | -2 | **11** | 0 | **16** | +3 |
| **2** | -4 | **7** | -2 | **12** | +1 | **17** | +3 |
| **3** | -4 | **8** | -1 | **13** | +1 | **18** | +4 |
| **4** | -3 | **9** | -1 | **14** | +2 | **19** | +4 |
| **5** | -3 | **10** | 0 | **15** | +2 | **20** | +5 |

but instead I get a inline text just like @addnot is seeing.

**Comment by NoahRic** [comment]
Tables aren't part of standard markdown, and that's really all the extension claims to support. Sorry :-/
